version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/rdsauth
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/rdsauth
    description: rdsauth is a tool to generate an auth token used to connect to a db with IAM credentials.
    license: MIT
    maintainer: "Genki Sugawara <sugawara@winebarrel.jp>"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
